#!/bin/bash

KEYWORDS=( "SHOW" "DROP" "SELECT" "FROM" "WHERE" )

parse_query() {
	LINE=""
	i=0
	#dependancy on first query word, prevents from using dumb constructions 	eg. DROP "table_name" SELECT "something"

	for word in $QUERY; do
		if [[ ${KEYWORDS[@]} =~ ${word^^} ]]; then
			TO_PARSE[$i]=$LINE
			i=$(( $i + 1 )) 		
			
			LINE=${word^^}		
		else
			LINE="$LINE $word"
		
		fi	       
	done
	
	TO_PARSE[$i]=$LINE
	QUERY=""
	for FUNCTION in "${TO_PARSE[@]}"; do
		echo "$FUNCTION"
		RETURN_VAL=$($FUNCTION)
		if [[ "$RETURN_VAL" != "" ]]; then
			PROMPT="$PROMPT$RETURN_VAL | "	
			echo "$PROMPT"
		fi
		#echo "$PROMPT"
		$FUNCTION 
		#echo $TABLE_NAME
		#echo "$RETURN_VAL"
        done
	echo "$RETURN_VAL"
        if [[ "$RETURN_VAL" != "" ]]; then
                PROMPT="$PROMPT$RETURN_VAL | "
        fi

	echo "$PROMPT"

}

FROM () {
        if [[ $# -gt 1 ]]; then
                echo "Syntax error. Found more than 1 table to search in!"
                return 1
        fi

        if [[ $(ls tables | grep -w $1) == "$1" ]]; then
                TABLE_NAME=$1
		echo "cat tables/$TABLE_NAME"
		return 0

        else
                echo "Syntax error. No table named $1 found!"
                return 1
        fi
}

SELECT () {
	COLUMNS=$@
	N_O_COLUMNS=$#
	
	if [[ $N_O_COLUMNS -eq 0 ]]; then
		echo "Syntax error. No columns found!"
		return 1
	fi

	if [[ "$COLUMNS" == "*" ]]; then
		echo "essa!"
		echo "awk -F ';' {print}"
		return 0
	fi


}

WHERE () {
	echo $@
}

while [ true ]; do 
	echo -n "Enter query: "
	read QUERY
	
	if [ "${QUERY^^}" == "EXIT" ]; then
		break
	else
		parse_query $QUERY
	fi
	
		

done
